/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as LoginRouteImport } from './../routes/$login'
import { Route as AdsDottxtRouteImport } from './../routes/ads[.]txt'
import { Route as ConfidentialiteRouteImport } from './../routes/confidentialite'
import { Route as DesignRouteImport } from './../routes/design'
import { Route as RobotsDottxtRouteImport } from './../routes/robots[.]txt'
import { Route as LoginManifestDotwebmanifestRouteImport } from './../routes/$login_.manifest[.]webmanifest'
import { Route as LoginObsRouteImport } from './../routes/$login_.obs'
import { Route as AuthSignoutRouteImport } from './../routes/auth/signout'
import { Route as AuthTwitchRouteImport } from './../routes/auth/twitch'
import { Route as TwitchEventsubRouteImport } from './../routes/twitch/eventsub'
import { Route as LoginArchivesCodeRouteImport } from './../routes/$login_.archives.$code'
import { Route as AuthTwitchCallbackRouteImport } from './../routes/auth/twitch.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/$login',
  path: '/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsDottxtRoute = AdsDottxtRouteImport.update({
  id: '/ads.txt',
  path: '/ads.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginManifestDotwebmanifestRoute =
  LoginManifestDotwebmanifestRouteImport.update({
    id: '/$login_/manifest.webmanifest',
    path: '/$login/manifest.webmanifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginObsRoute = LoginObsRouteImport.update({
  id: '/$login_/obs',
  path: '/$login/obs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignoutRoute = AuthSignoutRouteImport.update({
  id: '/auth/signout',
  path: '/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwitchRoute = AuthTwitchRouteImport.update({
  id: '/auth/twitch',
  path: '/auth/twitch',
  getParentRoute: () => rootRouteImport,
} as any)
const TwitchEventsubRoute = TwitchEventsubRouteImport.update({
  id: '/twitch/eventsub',
  path: '/twitch/eventsub',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginArchivesCodeRoute = LoginArchivesCodeRouteImport.update({
  id: '/$login_/archives/$code',
  path: '/$login/archives/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwitchCallbackRoute = AuthTwitchCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthTwitchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$login': typeof LoginRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/design': typeof DesignRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/$login/manifest.webmanifest': typeof LoginManifestDotwebmanifestRoute
  '/$login/obs': typeof LoginObsRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/auth/twitch': typeof AuthTwitchRouteWithChildren
  '/twitch/eventsub': typeof TwitchEventsubRoute
  '/$login/archives/$code': typeof LoginArchivesCodeRoute
  '/auth/twitch/callback': typeof AuthTwitchCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$login': typeof LoginRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/design': typeof DesignRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/$login/manifest.webmanifest': typeof LoginManifestDotwebmanifestRoute
  '/$login/obs': typeof LoginObsRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/auth/twitch': typeof AuthTwitchRouteWithChildren
  '/twitch/eventsub': typeof TwitchEventsubRoute
  '/$login/archives/$code': typeof LoginArchivesCodeRoute
  '/auth/twitch/callback': typeof AuthTwitchCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$login': typeof LoginRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/design': typeof DesignRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/$login_/manifest.webmanifest': typeof LoginManifestDotwebmanifestRoute
  '/$login_/obs': typeof LoginObsRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/auth/twitch': typeof AuthTwitchRouteWithChildren
  '/twitch/eventsub': typeof TwitchEventsubRoute
  '/$login_/archives/$code': typeof LoginArchivesCodeRoute
  '/auth/twitch/callback': typeof AuthTwitchCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$login'
    | '/ads.txt'
    | '/confidentialite'
    | '/design'
    | '/robots.txt'
    | '/$login/manifest.webmanifest'
    | '/$login/obs'
    | '/auth/signout'
    | '/auth/twitch'
    | '/twitch/eventsub'
    | '/$login/archives/$code'
    | '/auth/twitch/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$login'
    | '/ads.txt'
    | '/confidentialite'
    | '/design'
    | '/robots.txt'
    | '/$login/manifest.webmanifest'
    | '/$login/obs'
    | '/auth/signout'
    | '/auth/twitch'
    | '/twitch/eventsub'
    | '/$login/archives/$code'
    | '/auth/twitch/callback'
  id:
    | '__root__'
    | '/'
    | '/$login'
    | '/ads.txt'
    | '/confidentialite'
    | '/design'
    | '/robots.txt'
    | '/$login_/manifest.webmanifest'
    | '/$login_/obs'
    | '/auth/signout'
    | '/auth/twitch'
    | '/twitch/eventsub'
    | '/$login_/archives/$code'
    | '/auth/twitch/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdsDottxtRoute: typeof AdsDottxtRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  DesignRoute: typeof DesignRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  LoginManifestDotwebmanifestRoute: typeof LoginManifestDotwebmanifestRoute
  LoginObsRoute: typeof LoginObsRoute
  AuthSignoutRoute: typeof AuthSignoutRoute
  AuthTwitchRoute: typeof AuthTwitchRouteWithChildren
  TwitchEventsubRoute: typeof TwitchEventsubRoute
  LoginArchivesCodeRoute: typeof LoginArchivesCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$login': {
      id: '/$login'
      path: '/$login'
      fullPath: '/$login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads.txt': {
      id: '/ads.txt'
      path: '/ads.txt'
      fullPath: '/ads.txt'
      preLoaderRoute: typeof AdsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$login_/manifest.webmanifest': {
      id: '/$login_/manifest.webmanifest'
      path: '/$login/manifest.webmanifest'
      fullPath: '/$login/manifest.webmanifest'
      preLoaderRoute: typeof LoginManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$login_/obs': {
      id: '/$login_/obs'
      path: '/$login/obs'
      fullPath: '/$login/obs'
      preLoaderRoute: typeof LoginObsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signout': {
      id: '/auth/signout'
      path: '/auth/signout'
      fullPath: '/auth/signout'
      preLoaderRoute: typeof AuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/twitch': {
      id: '/auth/twitch'
      path: '/auth/twitch'
      fullPath: '/auth/twitch'
      preLoaderRoute: typeof AuthTwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twitch/eventsub': {
      id: '/twitch/eventsub'
      path: '/twitch/eventsub'
      fullPath: '/twitch/eventsub'
      preLoaderRoute: typeof TwitchEventsubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$login_/archives/$code': {
      id: '/$login_/archives/$code'
      path: '/$login/archives/$code'
      fullPath: '/$login/archives/$code'
      preLoaderRoute: typeof LoginArchivesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/twitch/callback': {
      id: '/auth/twitch/callback'
      path: '/callback'
      fullPath: '/auth/twitch/callback'
      preLoaderRoute: typeof AuthTwitchCallbackRouteImport
      parentRoute: typeof AuthTwitchRoute
    }
  }
}

interface AuthTwitchRouteChildren {
  AuthTwitchCallbackRoute: typeof AuthTwitchCallbackRoute
}

const AuthTwitchRouteChildren: AuthTwitchRouteChildren = {
  AuthTwitchCallbackRoute: AuthTwitchCallbackRoute,
}

const AuthTwitchRouteWithChildren = AuthTwitchRoute._addFileChildren(
  AuthTwitchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdsDottxtRoute: AdsDottxtRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  DesignRoute: DesignRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  LoginManifestDotwebmanifestRoute: LoginManifestDotwebmanifestRoute,
  LoginObsRoute: LoginObsRoute,
  AuthSignoutRoute: AuthSignoutRoute,
  AuthTwitchRoute: AuthTwitchRouteWithChildren,
  TwitchEventsubRoute: TwitchEventsubRoute,
  LoginArchivesCodeRoute: LoginArchivesCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
